### ISSUE TITLE
android.view.InflateException in EditTextPreference

### ISSUE THREAD

**Issue by Kahtaf** [michael-rapp/AndroidMaterialPreferences#16] opened 2017-11-20 00:01 UTC
Hi, thanks for the great library. I use it in several of my apps. I am running into a peculiar issue a few users have reported on Samsung Galaxy Tabs running Android 4.4 with the EditTextPreference. The app crashes as soon as the EditTextPreference is opened. I can't reproduce it myself, but is it possible to at least catch the error? Let me know if any more information is needed, thanks. 

`android.view.InflateException: 
  at android.view.LayoutInflater.createView (LayoutInflater.java:626)
  at android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:702)
  at android.view.LayoutInflater.inflate (LayoutInflater.java:470)
  at android.view.LayoutInflater.inflate (LayoutInflater.java:398)
  at android.view.LayoutInflater.inflate (LayoutInflater.java:354)
  at android.view.View.inflate (View.java:18457)
  at de.mrapp.android.preference.EditTextPreference.onPrepareDialog (EditTextPreference.java:346)
  at de.mrapp.android.preference.DialogPreference.showDialog (DialogPreference.java:1001)
  at de.mrapp.android.preference.DialogPreference.onClick (DialogPreference.java:2161)
  at android.preference.Preference.performClick (Preference.java:1052)
  at android.preference.PreferenceScreen.onItemClick (PreferenceScreen.java:229)
  at android.widget.AdapterView.performItemClick (AdapterView.java:308)
  at android.widget.AbsListView.performItemClick (AbsListView.java:1509)
  at android.widget.AbsListView$PerformClick.run (AbsListView.java:3471)
  at android.widget.AbsListView.onTouchUp (AbsListView.java:4849)
  at android.widget.AbsListView.onTouchEvent (AbsListView.java:4609)
  at android.view.View.dispatchTouchEvent (View.java:8135)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2425)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2149)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2431)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2164)
  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent (PhoneWindow.java:2295)
  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1622)
  at android.app.Activity.dispatchTouchEvent (Activity.java:2565)
  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:68)
  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:68)
  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent (PhoneWindow.java:2243)
  at android.view.View.dispatchPointerEvent (View.java:8343)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:4768)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4634)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4192)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4246)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4215)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4326)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4223)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4383)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4192)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4246)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4215)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4223)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4192)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:6557)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:6474)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:6445)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:6410)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:6637)
  at android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:185)
  at android.os.MessageQueue.nativePollOnce (Native Method)
  at android.os.MessageQueue.next (MessageQueue.java:138)
  at android.os.Looper.loop (Looper.java:131)
  at android.app.ActivityThread.main (ActivityThread.java:5602)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1283)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1099)
  at dalvik.system.NativeStart.main (Native Method)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Constructor.constructNative (Native Method)
  at java.lang.reflect.Constructor.newInstance (Constructor.java:423)
  at android.view.LayoutInflater.createView (LayoutInflater.java:600)`

**Comment by michael-rapp** [comment] 2017-11-20 00:17
I wasn't able to reproduce it using Android 4.4. on an emulator either. It is hard to fix something that is not reproducable. Catching the exception is not really a solution either, because that will cause the dialog to be empty or even invisible.

**Comment by michael-rapp** [comment] 2018-01-05 13:01
@Kahtaf The source of this issue definitely is the library [AndroidMaterialValidation](https://github.com/michael-rapp/AndroidMaterialValidation), which is used by this project. You have opened [this](https://github.com/michael-rapp/AndroidMaterialValidation/issues/3) issue for the other library. Both problems seem to have the same root cause. Do you agree?

**Comment by Kahtaf** [comment] 2018-01-05 14:28
@michael-rapp seems they both have the same root cause. Thanks for looking into this.

**Comment by michael-rapp** [comment] 2018-01-05 14:49
I fixed https://github.com/michael-rapp/AndroidMaterialValidation/issues/3 and updated this library to version 3.1.1 in order to use the updated version with the bugfix included. I am optimistic that this solves your problems and therefore will close this issue. If the problems persist, feel free to reopen it.

**Closed by michael-rapp** 2018-01-05 14:49 UTC
Labels: bug
